### PR TITLE
virEventAsyncIOImpl patches

### PR DESCRIPTION
**Pull request by woju**
Those patches are went to libvirt-list. Can we carry them now, and drop them later? Anyway, they'll happen at no earlier than libvirt*-3.2.0, but we still have 2.5.

### CODE REVIEW

**Comment by marmarek** [comment]
1. Patch do not apply
2. Should we update libvirt to 3.1.0 first?

**Comment by woju** [comment]
1. This version is for 2.5.0 (current HEAD).
2. Do we have another reasons for upgrading to 3.1.0? This runs fine on 2.5.0, so there is no hurry.

**Comment by marmarek** [comment]
> Do we have another reasons for upgrading to 3.1.0? This runs fine on 2.5.0, so there is no hurry.

Just easier to maintain patches until got accepted upstream. Especially when we need some new patches (like now) - better chance to apply exactly the same as sent upstream, instead of back/forward porting.

**Comment by woju** [comment]
Do as you wish. I have no opinion. The patches differ in `libvirt-python.spec.in`, which we don't use.

**Comment by marmarek** [comment]
cherry-picked

**Comment by woju** [comment]
Why cherry-picked and not merged or fast-forwarded?

**Comment by woju** [comment]
Correction: for fc25 we do have to have libvirt-python >= 3.0.0, because of this commit: libvirt/libvirt-python@a99e9fe.

**Comment by marmarek** [comment]
> Why cherry-picked and not merged or fast-forwarded?

Because it wasn't fast-forward anymore after my force-push.

> Correction: for fc25 we do have to have libvirt-python >= 3.0.0, because of this commit: libvirt/libvirt-python@a99e9fe.

Already noticed this: https://travis-ci.org/marmarek/qubes-core-libvirt/jobs/213684966

**Comment by woju** [comment]
OK, I give up on trying to bump this. I got this error:

```
./util/virerror.h:182:50: note: in definition of macro 'virReportError'
                          __FUNCTION__, __LINE__, __VA_ARGS__)
                                                  ^~~~~~~~~~~
conf/domain_conf.c:19330:69: error: 'virDomainRedirFilterDef {aka struct _virDomainRedirFilterDef}' has no member named 'xen_features'
                                    virTristateSwitchTypeToString(dst->xen_features[i]));
                                                                     ^
./util/virerror.h:182:50: note: in definition of macro 'virReportError'
                          __FUNCTION__, __LINE__, __VA_ARGS__)
                                                  ^~~~~~~~~~~
```

This is caused by e820 patch, but I don't know how to fix it up.

**Comment by marmarek** [comment]
Patch hit wrong function... Just pushed updates to core3-devel branch (compile tested only).
BTW there are compile warnings:
```
libvirt-override.c:5288:21: warning: unused variable 'cff' [-Wunused-variable]

     virFreeCallback cff;

                     ^~~

libvirt-override.c:5286:15: warning: unused variable 'ff' [-Wunused-variable]

     PyObject *ff;

               ^~

libvirt-override.c:5285:15: warning: unused variable 'opaque' [-Wunused-variable]

     PyObject *opaque;

               ^~~~~~

libvirt-override.c: In function 'libvirt_virEventRemoveTimeoutFunc':

libvirt-override.c:5406:21: warning: unused variable 'cff' [-Wunused-variable]

     virFreeCallback cff;

                     ^~~

libvirt-override.c:5404:15: warning: unused variable 'ff' [-Wunused-variable]

     PyObject *ff;

               ^~

libvirt-override.c:5403:15: warning: unused variable 'opaque' [-Wunused-variable]

     PyObject *opaque;

               ^~~~~~
```
Harmless, right?

**Comment by woju** [comment]
Right. Not enough code removed. That means I will have to amend my patches on libvirt-list.

**Pull request closed without merging**
